/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luke.projectaurora.graphics;

import com.luke.projectaurora.core.LedGraphicHandler;
import com.luke.projectaurora.entities.LedLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Luke
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form newPanelLeds
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ledPanel = new javax.swing.JPanel();
        ledSettingsPanel = new javax.swing.JPanel();
        ledLayoutLabel = new javax.swing.JLabel();
        layoutComboBox = new javax.swing.JComboBox<>();
        brightnessPanel = new com.luke.projectaurora.graphics.BrightnessPanel();
        animationLabel = new javax.swing.JLabel();
        animationComboBox = new javax.swing.JComboBox<>();
        presetLabel = new javax.swing.JLabel();
        presetComboBox = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        oledSettingsPanel = new javax.swing.JPanel();
        topLeftLabel = new javax.swing.JLabel();
        topLeftComboBox = new javax.swing.JComboBox<>();
        topRightLabel = new javax.swing.JLabel();
        topRightComboBox = new javax.swing.JComboBox<>();
        bottomLeftLabel = new javax.swing.JLabel();
        bottomLeftComboBox = new javax.swing.JComboBox<>();
        bottomRightLabel = new javax.swing.JLabel();
        bottomRightComboBox = new javax.swing.JComboBox<>();
        oledLayoutLabel = new javax.swing.JLabel();
        oledLayoutComboBox = new javax.swing.JComboBox<>();
        showLogoLabel = new javax.swing.JLabel();
        logoComboBox = new javax.swing.JComboBox<>();
        macroPanel = new javax.swing.JPanel();
        panelComm1 = new com.luke.projectaurora.graphics.PanelComm();

        ledPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Leds"));

        ledSettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Led settings"));

        ledLayoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ledLayoutLabel.setText("Layout:");

        layoutComboBox.setModel(new DefaultComboBoxModel(LedLayout.values()));
        layoutComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                layoutComboBoxItemStateChanged(evt);
            }
        });

        animationLabel.setText("Animation:");

        animationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        presetLabel.setText("Preset:");

        presetComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deleteButton.setText("Delete");

        addButton.setText("Add");

        setButton.setText("Set...");

        javax.swing.GroupLayout ledSettingsPanelLayout = new javax.swing.GroupLayout(ledSettingsPanel);
        ledSettingsPanel.setLayout(ledSettingsPanelLayout);
        ledSettingsPanelLayout.setHorizontalGroup(
            ledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ledSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brightnessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(ledSettingsPanelLayout.createSequentialGroup()
                        .addGroup(ledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(presetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ledLayoutLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(animationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(layoutComboBox, 0, 122, Short.MAX_VALUE)
                            .addComponent(animationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(presetComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ledSettingsPanelLayout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(setButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ledSettingsPanelLayout.setVerticalGroup(
            ledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ledSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brightnessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(layoutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ledLayoutLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(animationLabel)
                    .addComponent(animationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presetLabel)
                    .addComponent(presetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton)
                    .addComponent(addButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        oledSettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("OLED settings"));

        topLeftLabel.setText("top Left:");

        topLeftComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        topRightLabel.setText("top right:");

        topRightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bottomLeftLabel.setText("bottom left:");

        bottomLeftComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bottomRightLabel.setText("bottom right:");

        bottomRightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        oledLayoutLabel.setText("Layout:");

        oledLayoutComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        showLogoLabel.setText("show logo:");

        logoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout oledSettingsPanelLayout = new javax.swing.GroupLayout(oledSettingsPanel);
        oledSettingsPanel.setLayout(oledSettingsPanelLayout);
        oledSettingsPanelLayout.setHorizontalGroup(
            oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oledSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(topLeftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bottomLeftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(oledLayoutLabel)
                    .addComponent(showLogoLabel))
                .addGap(18, 18, 18)
                .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oledLayoutComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(oledSettingsPanelLayout.createSequentialGroup()
                        .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(logoComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 94, Short.MAX_VALUE)
                            .addComponent(topLeftComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bottomLeftComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bottomRightLabel)
                            .addComponent(topRightLabel))
                        .addGap(18, 18, 18)
                        .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topRightComboBox, 0, 103, Short.MAX_VALUE)
                            .addComponent(bottomRightComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        oledSettingsPanelLayout.setVerticalGroup(
            oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oledSettingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oledLayoutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oledLayoutLabel))
                .addGap(18, 18, 18)
                .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topLeftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topLeftLabel)
                    .addComponent(topRightLabel)
                    .addComponent(topRightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottomLeftLabel)
                    .addComponent(bottomLeftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottomRightLabel)
                    .addComponent(bottomRightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(oledSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showLogoLabel))
                .addGap(22, 22, 22))
        );

        macroPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Macro Keys"));

        javax.swing.GroupLayout macroPanelLayout = new javax.swing.GroupLayout(macroPanel);
        macroPanel.setLayout(macroPanelLayout);
        macroPanelLayout.setHorizontalGroup(
            macroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        macroPanelLayout.setVerticalGroup(
            macroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ledSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(oledSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ledPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(macroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelComm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelComm1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ledPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ledSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oledSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(macroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void layoutComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_layoutComboBoxItemStateChanged
        LedGraphicHandler.getInstance().switchLayout((LedLayout) evt.getItem());
    }//GEN-LAST:event_layoutComboBoxItemStateChanged

    public JButton getAddButton() {
        return addButton;
    }

    public JComboBox<String> getAnimationComboBox() {
        return animationComboBox;
    }

    public JLabel getAnimationLabel() {
        return animationLabel;
    }

    public JComboBox<String> getBottomLeftComboBox() {
        return bottomLeftComboBox;
    }

    public JLabel getBottomLeftLabel() {
        return bottomLeftLabel;
    }

    public JComboBox<String> getBottomRightComboBox() {
        return bottomRightComboBox;
    }

    public JLabel getBottomRightLabel() {
        return bottomRightLabel;
    }

    public BrightnessPanel getBrightnessPanel() {
        return brightnessPanel;
    }

    public JButton getDeleteButton() {
        return deleteButton;
    }

    public JComboBox<String> getLayoutComboBox() {
        return layoutComboBox;
    }

    public JLabel getLedLayoutLabel() {
        return ledLayoutLabel;
    }

    public JPanel getLedPanel() {
        return ledPanel;
    }

    public JPanel getLedSettingsPanel() {
        return ledSettingsPanel;
    }

    public JComboBox<String> getLogoComboBox() {
        return logoComboBox;
    }

    public JPanel getMacroPanel() {
        return macroPanel;
    }

    public JComboBox<String> getOledLayoutComboBox() {
        return oledLayoutComboBox;
    }

    public JLabel getOledLayoutLabel() {
        return oledLayoutLabel;
    }

    public JPanel getOledSettingsPanel() {
        return oledSettingsPanel;
    }

    public JComboBox<String> getPresetComboBox() {
        return presetComboBox;
    }

    public JLabel getPresetLabel() {
        return presetLabel;
    }

    public JButton getSetButton() {
        return setButton;
    }

    public JLabel getShowLogoLabel() {
        return showLogoLabel;
    }

    public JComboBox<String> getTopLeftComboBox() {
        return topLeftComboBox;
    }

    public JLabel getTopLeftLabel() {
        return topLeftLabel;
    }

    public JComboBox<String> getTopRightComboBox() {
        return topRightComboBox;
    }

    public JLabel getTopRightLabel() {
        return topRightLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> animationComboBox;
    private javax.swing.JLabel animationLabel;
    private javax.swing.JComboBox<String> bottomLeftComboBox;
    private javax.swing.JLabel bottomLeftLabel;
    private javax.swing.JComboBox<String> bottomRightComboBox;
    private javax.swing.JLabel bottomRightLabel;
    private com.luke.projectaurora.graphics.BrightnessPanel brightnessPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> layoutComboBox;
    private javax.swing.JLabel ledLayoutLabel;
    private javax.swing.JPanel ledPanel;
    private javax.swing.JPanel ledSettingsPanel;
    private javax.swing.JComboBox<String> logoComboBox;
    private javax.swing.JPanel macroPanel;
    private javax.swing.JComboBox<String> oledLayoutComboBox;
    private javax.swing.JLabel oledLayoutLabel;
    private javax.swing.JPanel oledSettingsPanel;
    private com.luke.projectaurora.graphics.PanelComm panelComm1;
    private javax.swing.JComboBox<String> presetComboBox;
    private javax.swing.JLabel presetLabel;
    private javax.swing.JButton setButton;
    private javax.swing.JLabel showLogoLabel;
    private javax.swing.JComboBox<String> topLeftComboBox;
    private javax.swing.JLabel topLeftLabel;
    private javax.swing.JComboBox<String> topRightComboBox;
    private javax.swing.JLabel topRightLabel;
    // End of variables declaration//GEN-END:variables
}
